services:
  - type: web
    name: university-timetable-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -u start_web.py
    autoDeploy: true

  - type: worker
    name: university-timetable-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -u -m app.bot.main
    autoDeploy: true

  - type: worker
    name: university-timetable-scheduler
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -u -m app.scheduler.worker
    autoDeploy: true
