services:
  - type: redis
    name: university-timetable-redis
    plan: free
    maxmemoryPolicy: noeviction

  - type: web
    name: university-timetable-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -u start_web.py
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: university-timetable-redis
          property: connectionString
